#!/usr/bin/env bash

APP="proxy_ex"

BUILD_HOST="build.proxy.com"
BUILD_USER="builder"
BUILD_AT="/tmp/edeliver/proxy_ex/builds"

STAGING_HOSTS="stage.proxy.com"
STAGING_USER="staging"

PRODUCTION_HOSTS="deploy1.proxy.com deploy2.proxy.com"
PRODUCTION_USER="production"
DELIVER_TO="/home/user"
