#!/usr/bin/env bash

APP="nosbyte_proxy"

BUILD_HOST="build.nosbyte_proxy.com"
BUILD_USER="builder"
BUILD_AT="/tmp/edeliver/nosbyte_proxy/builds"

STAGING_HOSTS="stage.nosbyte_proxy.com"
STAGING_USER="staging"

PRODUCTION_HOSTS="deploy1.nosbyte_proxy.com deploy2.nosbyte_proxy.com"
PRODUCTION_USER="production"
DELIVER_TO="/home/user"
